export const FETCH_ROOMS_PROGRESS = 'FETCH_ROOMS_PROGRESS';
export const FETCH_ROOMS_FINISHED = 'FETCH_ROOMS_FINISHED';

export const SOCKET_OPENED = 'SOCKET_OPENED';
export const SOCKET_CLOSED = 'SOCKET_CLOSED';
export const SOCKET_ERROR = 'SOCKET_ERROR';
export const SOCKET_DATA = 'SOCKET_DATA';
