export const SET_USERNAME = 'SET_USERNAME';

export const FETCH_ROOMS_PROGRESS = 'FETCH_ROOMS_PROGRESS';
export const FETCH_ROOMS_FINISHED = 'FETCH_ROOMS_FINISHED';

export const ROOM_USERS = 'ROOM_USERS';
export const ROOM_MESSAGE = 'ROOM_MESSAGE';
